swagger: "2.0"
info:
  version: "0.0.1"
  title: Blab
host: localhost:3000
basePath: /
schemes:
  # tip: remove http to make production-grade
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /auth:
    x-swagger-router-controller: request_router
    post:
      description: Responds with json web token (JWT) to be used for subsequent requests
      produces:
        - text/plain
      operationId: login
      tags:
        - auth
      parameters:
        -
          name: Credentials
          in: body
          description: Credentials to receive JWT
          required: true
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
                format: email
              password:
                type: string
                format: password
      responses:
        "200":
          description: Success
          schema:
            type: string
  /ledgers:
    x-swagger-router-controller: request_router
    get:
      description: Get balance of all accounts
      operationId: getAll
      tags:
        - ledgers
      parameters:
        - $ref: "#/parameters/jwtheader"
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/LedgerEntry"
  /ledgers/{id}:
    x-swagger-router-controller: request_router
    get:
      description: Get balance for single account
      operationId: getBalanceFor
      parameters:
        - $ref: "#/parameters/jwtheader"
        - name: id
          in: path
          description: account id
          required: true
          type: string
      tags:
        - ledgers
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/LedgerEntry"
  /transactions:
    x-swagger-router-controller: request_router
    post:
      description: Moves tokens from current user to specified account
      operationId: moveTokens
      tags:
        - transactions
      parameters:
        - $ref: "#/parameters/jwtheader"
        - name: transaction
          in: body
          description: recipient and amount
          required: true
          schema:
            type: object
            required:
              - to
              - amount
            properties:
              to:
                type: string
              amount:
                type: number
      responses:
        "201":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/DefaultSuccessResponse"
  /exchange:
    x-swagger-router-controller: request_router
    post:
      description: exchange blab to euro
      operationId: toEuro
      tags:
        - exchange
      parameters:
        - $ref: "#/parameters/jwtheader"
        - name: exchange
          in: body
          description: amount to exchange to euro
          required: true
          schema:
            type: object
            required:
              - amount
              - recipient
            properties:
              amount:
                type: number
              recipient:
                type: string
      responses:
        "201":
          description: Success
          schema:
            $ref: "#/definitions/DefaultSuccessResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  DefaultSuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
  LedgerEntry:
    properties:
      ethereumAddress:
        type: string
      tokenAmount:
        type: number
      owner:
        type: string
parameters:
  jwtheader:
    name: Authorization
    in: header
    description: json web token
    required: true
    type: string