swagger: "2.0"
info:
  version: "0.0.1"
  title: Blab
host: localhost:3000
basePath: /
schemes:
  # tip: remove http to make production-grade
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /auth:
    x-swagger-router-controller: request_router
    post:
      description: Responds with json web token (JWT) to be used for subsequent requests
      produces:
        - text/plain
      operationId: login
      tags:
        - auth
      parameters:
        -
          name: Credentials
          in: body
          description: Credentials to receive JWT
          required: true
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
                format: email
              password:
                type: string
                format: password
      responses:
        "200":
          description: Success
          schema:
            type: string
  /ledgers:
    x-swagger-router-controller: request_router
    get:
      description: todo
      operationId: getAll
      tags:
        - ledgers
      parameters:
        - $ref: "#/parameters/jwtheader"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/DefaultSuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /ledgers/{id}:
    x-swagger-router-controller: request_router
    get:
      description: todo
      operationId: getBalanceFor
      parameters:
        - name: id
          in: path
          description: foo
          required: true
          type: string
      tags:
        - ledgers
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/DefaultSuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /transactions:
    x-swagger-router-controller: request_router
    post:
      description: asdf
      operationId: moveTokens
      tags:
        - transactions
      responses:
        "201":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/DefaultSuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /exchange:
    x-swagger-router-controller: request_router
    post:
      description: asdf
      operationId: toEuro
      tags:
        - exchange
      responses:
        "201":
          description: Success
          schema:
            $ref: "#/definitions/DefaultSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  DefaultSuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
parameters:
  jwtheader:
    name: Authorization
    in: header
    description: json web token
    required: true
    type: string